import type { Metadata } from "next";
import { Tektur } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { SmoothScroll } from "@/components/ui/SmoothScroll/SmoothScroll";
import ScrollTop from "@/components/ui/ScrollToTop/ScrollTop";

const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${tektur.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <SmoothScroll>
          <Header />
          <main>{children}</main>
          <Footer />
          <ScrollTop />
        </SmoothScroll>
      </body>
    </html>
  );
}
